[build]
  command = "npm run build"
  publish = "dist-prod"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[[redirects]]
  from = "/guest/*"
  to = "/guest/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
