[build]
  command = "npm run build"
  publish = "dist-prod"

[[redirects]]
  from = "/guest/*"
  to = "/guest/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
